name: app_dictionary
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9
  firebase_crashlytics: ^3.4.18
  validatorless: ^1.2.3
  top_snackbar_flutter: ^3.1.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true